version: '3.7'

services:
  nfl-rushing-backend:
    build:
      context: ./backend
      target: dev
      #target: prod
    ports:
      - 8100:4000
    environment:
      DB_DATABASE: "${POSTGRES_DB}"
      DB_HOSTNAME: nfl-rushing-db
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_USERNAME: "${POSTGRES_USER}"
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nfl-rushing-db/${POSTGRES_DB}"
      SECRET_KEY_BASE: tntzNbgn0WrwREA8oYkl0Medqp3Cbxzdv/DtVL8R3GQprb+6N1Jtq4OKt3NA5vG1
    init: true
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - ./rushing.json:/app/priv/repo/rushing.json:ro
      - nfl-rushing-backend__build:/app/_build
      - nfl-rushing-backend__deps:/app/deps
    depends_on:
      - nfl-rushing-db
  
  nfl-rushing-db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - nfl-rushing-db__data:/var/lib/postgresql/data

  nfl-rushing-frontend:
    build:
      context: ./frontend
      # Use the dev target to run a Vue server with code reloading
      # Use the prod target to run Nginx serving a static build
      target: dev
      #target: prod
    ports:
      # Dev server
      - 8000:8080
      # Prod server
      - 8001:80
    environment:
      VUE_APP_API_URL: http://nfl-rushing-backend:4000
    init: true
    stdin_open: true
    tty: true
    # Don't mount the following volumes if running the prod target
    volumes:
      - ./frontend:/app
      - nfl-rushing-frontend__node_modules:/app/node_modules
    depends_on:
      - nfl-rushing-backend

volumes:
  nfl-rushing-backend__build:
  nfl-rushing-backend__deps:
  nfl-rushing-frontend__node_modules:
  nfl-rushing-db__data:
